version: "3"

services:
  server:
    image: ghcr.io/jackharrhy/server:latest
    build: .
    volumes:
      - ./data:/data
    environment:
      - SERVER_TOKEN=servertoken
      - SERVER_DB_LOCATION=/data/server.db
    ports:
      - 127.0.0.1:3000:3000
